language: objective-c
branches:
 only:
  - master
osx_image: xcode7.3
xcode_project: DateCalculator.xcodeproj
xcode_scheme: DateCalculatorTests
script:
  - xcodebuild test -project DateCalculator.xcodeproj -scheme DateCalculatorTests